

GET http://localhost:3001/user

### CRIA USER 
# @name createUser
POST http://localhost:3001/user
Content-Type: application/json

{
    "name": "Daniel",
    "email": "daniel@example.com",
    "password": "password123"
}

### SIGNIN
# @name signIn
POST http://localhost:3001/user/session
Content-Type: application/json

{
    "email": "daniel@example.com",
    "password": "password123"
}

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzk0ODU4MywiZXhwIjoxNzM0MDM0OTgzfQ.p82-ctKsV85V0lLMHb4elkB85XsIJndrCJ7e7vYvEQo


### DELETE USER
DELETE  http://localhost:3001/user
Authorization: Bearer {{accessToken}}



### GET USER
GET http://localhost:3001/user/profile
Authorization: Bearer {{accessToken}}

### GET INITIAL CARDS
### USE PARA DAR AS PRIMEIRAS CARTAS GRÁTIS PARA O USUÁRIO
### VOCE LINKA ATRAVÉS DO DECK ID
POST http://localhost:3001/user-card/get-initial
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "deckId": "f2d95b87-3320-47ea-9821-d37feaa8dfb6"
}


### LISTA DE TODAS AS CARTAS QUE O USER POSSUI EM UM BARALHO
GET http://localhost:3001/user-card/f2d95b87-3320-47ea-9821-d37feaa8dfb6
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### CRIAR PARTIDA A PARTIR DE UM BARALHO
POST http://localhost:3001/match
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "deckId": "f2d95b87-3320-47ea-9821-d37feaa8dfb6"
}


### VER UMA PARTIDA
GET  http://localhost:3001/match/1a93f90e-38bd-4601-969c-6a800f707ac2
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### LISTAR HISTORICO DE PARTIDAS
GET  http://localhost:3001/match/matches
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### ATUALIZAR SHOTS
### EX: SE O USER BEBEU, APENAS COM O ID DA PARTIDA E DA CARTA OS SHOTS JA SAO SETADOS
PUT  http://localhost:3001/match
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "matchId": "1a93f90e-38bd-4601-969c-6a800f707ac2",
  "cardId": "d3fdf84e-a398-4177-b416-69025e71a72f"
}

### DELETAR PARTIDA
DELETE http://localhost:3001/match/a27193a3-885d-477b-895b-bf3599870266
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### CRIAR UM PACK 
POST http://localhost:3001/pack
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Pack Ultra",
  "price": 50,
  "quantity": 100
}


### BUSCAR UM PACK
GET  http://localhost:3001/pack/a27e134d-8ba7-43a6-8179-bb012d59dc5a
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### BUSCAR TODOS OS PACKS
GET  http://localhost:3001/pack/all
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### BUSCA A PREFERENCEID PARA GERAR O FRONT DO MP
POST http://localhost:3001/pack/purchase/preferenceId
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "packId": "48219d54-a431-43d5-a5ec-99710340efac" 
}



### COMPRAR PACK, NAO USE AINDA POIS MAIS INFORMACOES SERAO NECESSARIAS
POST http://localhost:3001/pack/purchase
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "packId": "48219d54-a431-43d5-a5ec-99710340efac" 
}
