

GET http://localhost:3000/user

###
# @name createUser
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Daniel",
    "email": "daniel@example.com",
    "password": "password123"
}

###
DELETE  http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

###
# @name signIn
POST http://localhost:3000/user/session
Content-Type: application/json

{
    "email": "daniel@example.com",
    "password": "password123"
}

###
GET http://localhost:3000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

###
POST http://localhost:3000/user-card/get-initial
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

{
  "deckId": "f2d95b87-3320-47ea-9821-d37feaa8dfb6"
}


###
GET http://localhost:3000/user-card/f2d95b87-3320-47ea-9821-d37feaa8dfb6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo


###
POST http://localhost:3000/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

{
  "deckId": "f2d95b87-3320-47ea-9821-d37feaa8dfb6"
}

### other match
POST http://localhost:3000/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

{
  "deckId": "f2d95b87-3320-47ea-9821-d37feaa8dfb6"
}


###
GET  http://localhost:3000/match/1a93f90e-38bd-4601-969c-6a800f707ac2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo


###
GET  http://localhost:3000/match/matches
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

###
PUT  http://localhost:3000/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

{
  "matchId": "1a93f90e-38bd-4601-969c-6a800f707ac2",
  "cardId": "d3fdf84e-a398-4177-b416-69025e71a72f"
}

### other match
PUT  http://localhost:3000/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

{
  "matchId": "365934db-41f9-4159-8dfe-6a46cf2cc3fa",
  "cardId": "091368ea-312d-404a-9d0a-41677b954c5c"
}


###
DELETE http://localhost:3000/match/a27193a3-885d-477b-895b-bf3599870266
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo


### create pack
POST http://localhost:3000/pack
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

{
  "name": "Pack Ultra",
  "price": 50,
  "quantity": 100
}


###
GET  http://localhost:3000/pack/a27e134d-8ba7-43a6-8179-bb012d59dc5a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

###
GET  http://localhost:3000/pack/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo


### create pack
POST http://localhost:3000/pack/purchase
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

{
  "packId": "a27e134d-8ba7-43a6-8179-bb012d59dc5a" 
}

### create pack
PUT http://localhost:3000/pack/purchase/7d321eea-9faa-4e2e-8fdf-c6d2474dace1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzQyNjU1OCwiZXhwIjoxNzMzNTEyOTU4fQ.NZKJ93eUkV4ImAYDaracbmGSZvb4HpWtoV9tChdKKeo

{
  "userId": "8eb5c180-d434-44aa-819d-5517c78581ec",
  "status": "APPROVED"
}
