

GET http://localhost:3000/user

###
# @name createUser
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Daniel",
    "email": "daniel@example.com",
    "password": "password123"
}

###
DELETE  http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InpsYXRhbkBleGFtcGxlLmNvbSIsInN1YiI6IjI5MGEzZDc5LWVhYzUtNGYxNy04ZDlhLTU1ZTQ4MWU0NWM5OSIsImlhdCI6MTczMzMzMzc3OSwiZXhwIjoxNzMzNDIwMTc5fQ.s1_c151ZWCNmZnaZFKJO0u6myBG5fEg0aZuDiLp7ivQ

###
# @name signIn
POST http://localhost:3000/user/session
Content-Type: application/json

{
    "email": "daniel@example.com",
    "password": "password123"
}

###
GET http://localhost:3000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InpsYXRhbkBleGFtcGxlLmNvbSIsInN1YiI6ImVkZWJlMjBmLTQ0YWQtNGZiMi04NWI4LTBkYTg2Y2UzZTcwMyIsImlhdCI6MTczMzMzNDA1NiwiZXhwIjoxNzMzNDIwNDU2fQ.0TdGBnQ2QVMYxiOI5T0LXdDMm27zR4y3u3iB_EwfWMc

###
POST http://localhost:3000/user-card/get-initial
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzM1Nzg2NywiZXhwIjoxNzMzNDQ0MjY3fQ.J6dOrqYn4y34GCuTbtUg3R7K2bl-PFJdv4UaLu-T1qg

{
  "deckId": "f2d95b87-3320-47ea-9821-d37feaa8dfb6"
}


###
GET http://localhost:3000/user-card/f2d95b87-3320-47ea-9821-d37feaa8dfb6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbEBleGFtcGxlLmNvbSIsInN1YiI6IjhlYjVjMTgwLWQ0MzQtNDRhYS04MTlkLTU1MTdjNzg1ODFlYyIsImlhdCI6MTczMzM1Nzg2NywiZXhwIjoxNzMzNDQ0MjY3fQ.J6dOrqYn4y34GCuTbtUg3R7K2bl-PFJdv4UaLu-T1qg
